require "tmpdir"

# TODO(joesoftware): Make this do useful stuff.

desc "Bootstrap bundler and npm using brew"
task :bootstrap do
  # If we're here, ruby is already installed. Just ensure bundler is here.
  sh "gem install bundler --no-rdoc --no-ri"

  # Install npm.
  sh "brew update"
  sh "brew install npm"

  # Continue with install.
  Rake::Task[:install].invoke 
end

desc "Install dependencies for serving and development"
task :install do
  sh "bundle install --jobs 3 --retry=3 --deployment"
  sh "npm install"
end

desc "Run lint"
task :lint do
  sh "npm run-script lint"
end

desc "Run the development node server"
task :"serve" do
  sh "node ."
end
