@startuml

actor "Valued user" as user
participant "User's web\nbrowser" as browser
participant "Our fabulous\nweb server" as server
database "Much\ndata" as mysql
participant "Plenty of kitten\npictures" as store

user -> browser : navigates to our URL
browser -> server : requests URL
server -> browser : returns search page
user -> browser : types 'kittens' in search box
browser -> server : submits 'kittens' to search URL
server -> mysql : searches for 'kittens'
mysql -> server : returns list of kitten pictures
server <-> store : request list of kitten pictures
server -> browser : returns kitten pictures
browser -> user : user sees kittens

@enduml